include(ExternalProject)

set(GLFW_CMAKE_ARGS
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR> 
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
  -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
  -DBUILD_SHARED_LIBS=FALSE
)

ExternalProject_Add(libglfw
  PREFIX glfw_src
  GIT_REPOSITORY https://github.com/glfw/glfw.git
  GIT_TAG 3.2.1
  CMAKE_ARGS ${GLFW_CMAKE_ARGS}
  INSTALL_DIR ${PROJECT_SOURCE_DIR}/../vendor
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1
)

